module.exports = function (sesId,query,callback) { 
    var apiai=require('apiai');
	var app=apiai("a005521e4a574ad59ab090190ab7a5d8"); //Put the required access token for the bot
	var options={
		sessionId:sesId
	};
	var reply;
		//console.log(2);
		
		var request = app.textRequest(query, options);
		request.on('response',function(response){
		//console.log(3);
		//console.log(response.result.fulfillment.speech);
		//console.log(response);
		var Result=response.result;
		//console.log(Result.actionIncomplete);
			
			if(Result.metadata.intentName=='DeviceQuerry')
			{

						if(Result.actionIncomplete==false)

					{
						console.log("HERE IN THE CONDTION");

						//Call Ritam's function and set the reply manually if it false else give the reply generated by Dialogflow

						reply={"answer":Result.fulfillment.speech};
						callback(reply);

					}
					else
					{

						reply={"answer":Result.fulfillment.speech};
						//console.log(reply);
						callback(reply);
						
					}


			}
			else if(Result.metadata.intentName=='DeviceStartContext')
			{




						if(Result.actionIncomplete==false)

					{
						console.log("HERE IN THE CONDTION");

						//Call Ritam's function and set the reply manually if it false else give the reply generated by Dialogflow

						reply={"answer":Result.fulfillment.speech};
						callback(reply);

					}
					else
					{

						reply={"answer":Result.fulfillment.speech};
						//console.log(reply);
						callback(reply);
						
					}
			}
			else if(Result.metadata.intentName=='DeviceQuery - yes')

			{

				console.log(Result.contexts);
				console.log(Result.contexts.parameters);
				
				reply={"answer":Result.fulfillment.speech};
						//console.log(reply);
						callback(reply);

			}
			else if(Result.metadata.intentName=='DeviceStartContext - yes')
			{
				
				console.log(Result.contexts);
				console.log(Result.contexts.parameters);
				reply={"answer":Result.fulfillment.speech};
						//console.log(reply);
						callback(reply);
			}

			else{


				reply={"answer":Result.fulfillment.speech};
				callback(reply);


			}						

		
		});
		request.on('error',function(error){

		console.log(error);
		reply={"answer":"Sorry an error occured!!!"};

		callback(reply);
		});

		request.end();

		process.on('uncaughtExceptions',function(){
			console.log('Error');
		});
		//console.log(4);
		
		

};












