module.exports = function (sesId,query,callback) { 
    var apiai=require('apiai');
	var app=apiai("a005521e4a574ad59ab090190ab7a5d8"); //Put the required access token for the bot
	var options={
		sessionId:sesId
	};
	var reply;
		//console.log(2);
		
		var request = app.textRequest(query, options);
		request.on('response',function(response){
		//console.log(3);
		//console.log(response.result.fulfillment.speech);
		var Result=response.result;
		//console.log(Result.actionIncomplete);
			if(Result.actionIncomplete==false)

			{
				console.log("HERE IN THE CONDTION");

				//Call Ritam's function and set the reply manually if it false else give the reply generated by Dialogflow

				reply={"answer":"found it"};


			}
			else
			{

				reply={"answer":Result.fulfillment.speech};
				//console.log(reply);

				
			}

		callback(reply);
		});
		request.on('error',function(error){

		console.log(error);
		reply={"answer":"Sorry an error occured!!!"};

		callback(reply);
		});

		request.end();

		//console.log(4);
		
		

};












